src/Entity/Series.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Series
 *
 * @ORM\Table(name="series", uniqueConstraints={@ORM\UniqueConstraint(name="UNIQ_3A10012D85489131", columns={"imdb"})})
 * @ORM\Entity
 */
class Series
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     */
    private $title;

    /**
     * @var string|null
     *
     * @ORM\Column(name="plot", type="text", length=0, nullable=true)
     */
    private $plot;

    /**
     * @var string
     *
     * @ORM\Column(name="imdb", type="string", length=128, nullable=false)
     * @Assert\Regex("/^tt[0-9]{7,8}$/")
     */
    private $imdb;

    /**
     * @var string|null
     *
     * @ORM\Column(name="poster", type="blob", length=0, nullable=true)
     */
    private $poster;

    /**
     * @var string|null
     *
     * @ORM\Column(name="director", type="string", length=255, nullable=true)
     */
    private $director;

    /**
     * @var string|null
     *
     * @ORM\Column(name="youtube_trailer", type="string", length=255, nullable=true)
     */
    private $youtubeTrailer;

    /**
     * @var string|null
     *
     * @ORM\Column(name="awards", type="text", length=0, nullable=true)
     */
    private $awards;

    /**
     * @var int|null
     *
     * @ORM\Column(name="year_start", type="integer", nullable=true)
     */
    private $yearStart;

    /**
     * @var int|null
     *
     * @ORM\Column(name="year_end", type="integer", nullable=true)
     */
    private $yearEnd;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Actor", mappedBy="series")
     */
    private $actor;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Country", mappedBy="series")
     */
    private $country;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Genre", mappedBy="series")
     */
    private $genre;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="User", mappedBy="series")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="Rating", mappedBy="series")
     */
    private $ratings;

    /**
     * @ORM\OneToMany(targetEntity="Season", mappedBy="series")
     * @ORM\OrderBy({"number"="ASC"})
     */
    private $seasons;

    /**
     * @ORM\OneToMany(targetEntity="ExternalRating", mappedBy="series")
     */
    private $externalRating;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->actor = new ArrayCollection();
        $this->country = new ArrayCollection();
        $this->genre = new ArrayCollection();
        $this->user = new ArrayCollection();
        $this->ratings = new ArrayCollection();
        $this->seasons = new ArrayCollection();
        $this->externalRating = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPlot(): ?string
    {
        return $this->plot;
    }

    public function setPlot(?string $plot): self
    {
        $this->plot = $plot;

        return $this;
    }

    public function getImdb(): ?string
    {
        return $this->imdb;
    }

    public function setImdb(string $imdb): self
    {
        $this->imdb = $imdb;

        return $this;
    }

    public function getPoster()
    {
        return $this->poster;
    }

    public function getPosterImage()
    {
        return base64_encode(stream_get_contents($this->poster));
    }

    public function setPoster($poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(?string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getYoutubeTrailer(): ?string
    {
        return $this->youtubeTrailer;
    }

    public function getYoutubeTrailerEmbed(): ?string
    {
        $replace = "watch?v=";

        return str_replace($replace, "embed/", $this->youtubeTrailer);
    }

    public function setYoutubeTrailer(?string $youtubeTrailer): self
    {
        $this->youtubeTrailer = $youtubeTrailer;

        return $this;
    }

    public function getAwards(): ?string
    {
        return $this->awards;
    }

    public function setAwards(?string $awards): self
    {
        $this->awards = $awards;

        return $this;
    }

    public function getYearStart(): ?int
    {
        return $this->yearStart;
    }

    public function setYearStart(?int $yearStart): self
    {
        $this->yearStart = $yearStart;

        return $this;
    }

    public function getYearEnd(): ?int
    {
        return $this->yearEnd;
    }

    public function setYearEnd(?int $yearEnd): self
    {
        $this->yearEnd = $yearEnd;

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActor(): Collection
    {
        return $this->actor;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actor->contains($actor)) {
            $this->actor[] = $actor;
            $actor->addSeries($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actor->contains($actor)) {
            $this->actor->removeElement($actor);
            $actor->removeSeries($this);
        }

        return $this;
    }

    /**
     * @return Collection|Country[]
     */
    public function getCountry(): Collection
    {
        return $this->country;
    }

    public function addCountry(Country $country): self
    {
        if (!$this->country->contains($country)) {
            $this->country[] = $country;
            $country->addSeries($this);
        }

        return $this;
    }

    public function removeCountry(Country $country): self
    {
        if ($this->country->contains($country)) {
            $this->country->removeElement($country);
            $country->removeSeries($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenre(): Collection
    {
        return $this->genre;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genre->contains($genre)) {
            $this->genre[] = $genre;
            $genre->addSeries($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genre->contains($genre)) {
            $this->genre->removeElement($genre);
            $genre->removeSeries($this);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->addSeries($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
            $user->removeSeries($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setSeries($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getSeries() === $this) {
                $rating->setSeries(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setSeries($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->contains($season)) {
            $this->seasons->removeElement($season);
            // set the owning side to null (unless already changed)
            if ($season->getSeries() === $this) {
                $season->setSeries(null);
            }
        }

        return $this;
    }

    public function getExternalRating()
    {
        return $this->externalRating;
    }

    public function setExternalRating(?ExternalRating $externalRating): self
    {
        $this->externalRating = $externalRating;

        // set (or unset) the owning side of the relation if necessary
        $newSeries = null === $externalRating ? null : $this;
        if ($externalRating->getSeries() !== $newSeries) {
            $externalRating->setSeries($newSeries);
        }

        return $this;
    }

    public function addExternalRating(ExternalRating $externalRating): self
    {

src/Form/SeriesType.php
<?php

namespace App\Form;

use App\Entity\Series;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('plot')
            ->add('imdb')
            ->add('youtubeTrailer')
            ->add('awards')
            ->add('yearStart')
            ->add('yearEnd')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Series::class,
        ]);
    }
}

src/Controller/SeriesController.php
<?php

namespace App\Controller;

use App\Entity\Series;
use App\Entity\SeriesSearch;
use App\Form\RatingType;
use App\Form\SeriesSearchType;
use App\Form\UpdateRatingType;
use App\Repository\EpisodeRepository;
use App\Repository\ExternalRatingRepository;
use App\Repository\RatingRepository;
use App\Repository\SeasonRepository;
use App\Repository\SeriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/series")
 */
class SeriesController extends AbstractController
{
    private $seriesRepository;
    private $seasonRepository;
    private $ratingRepository;
    private $episodeRepository;
    private $externalRatingRepository;
    private $paginator;
    private $em;

    /**
     * @Route("", name="series_index", methods={"GET"})
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $series_search = new SeriesSearch();
        $form = $this->createForm(SeriesSearchType::class, $series_search);
        $form->handleRequest($request);

        $series = $this->paginator->paginate($this->seriesRepository->findSeriesBySearchFilter($series_search)->getResult(),
            $request->query->getInt('page', 1), 5);

        return $this->render('series/index.html.twig', [
            'series' => $series,
            'seriesSearch' => true,
            'searchForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/poster/{id}", name="poster_show", methods={"GET"})
     * @param Series $series
     * @return Response
     */
    public function show_poster(Series $series): Response
    {
        $poster = stream_get_contents($series->getPoster());

        $response = new Response($poster);
        $response->headers->set('Content-Type', 'image/jpg');

        return $response;
    }


    /**
     * @Route("/{id}", name="series_show", methods={"GET"})
     * @param Series $series the series that we want to show
     * @param Request $request
     * @return Response
     */
    public function show(Series $series, Request $request): Response
    {
        $form = $this->createForm(RatingType::class, null, array('series' => $series));

        $ratings = $this->paginator->paginate($this->ratingRepository->findBy(array('series' => $series), array('id' => 'DESC')),
            $request->query->getInt('page', 1), 7);

        $episodesWatchedByUser = [];
        $isSeriesFollowedByUser = false;
        if ($this->getUser()) {
            $episodesWatchedByUser = $this->episodeRepository->findEpisodeWatchedBySeriesAndUser($series, $this->getUser());
            $isSeriesFollowedByUser = $this->seriesRepository->isSeriesFollowedByUser($series, $this->getUser());
        }
        $isRatedByUser = $this->ratingRepository->isSeriesRatedByUser($series, $this->getUser());
        return $this->render('series/show.html.twig', [
            'series' => $series,
            'ratings' => $ratings,
            'isRatedByUser' => $isRatedByUser,
            'update' => $this->createForm(UpdateRatingType::class),
            'formRating' => $form->createView(),
            'episodesWatchedByUser' => $episodesWatchedByUser,
            'isSeriesFollowedByUser' => $isSeriesFollowedByUser,
        ]);
    }

    /**
     * @Route("/follow/{id}", name="follow_series", methods={"GET"})
     * @IsGranted("ROLE_USER",message="need to login")
     *
     * @param Series $series the series that we want to follow or unfollow
     * @return JsonResponse
     */
    public function followSeries(Series $series): JsonResponse
    {
        if ($this->getUser()->getSeries()->contains($series)) {
            $this->getUser()->removeSeries($series);
        } else {
            $this->getUser()->addSeries($series);
        }
        $this->getDoctrine()->getManager()->flush();

        return $this->json("OK");
    }

    /**
     * @Route("/followProfile/{id}", name="profile_follow_series", methods={"POST"})
     * @IsGranted("ROLE_USER")
     *
     * @param Series $series the series that we want to follow or unfollow
     * @return JsonResponse
     */
    public function followSeriesProfile(Series $series): Response
    {
        if ($this->getUser()->getSeries()->contains($series)) {
            $this->getUser()->removeSeries($series);
        } else {
            $this->getUser()->addSeries($series);
        }
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('profile_my_series');
    }

    /**
     * SeriesController constructor.
     * @param SeriesRepository $seriesRepository
     * @param PaginatorInterface $paginator
     * @param SeasonRepository $seasonRepository
     * @param RatingRepository $ratingRepository
     * @param EpisodeRepository $episodeRepository
     * @param ExternalRatingRepository $externalRatingRepository
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(SeriesRepository $seriesRepository, PaginatorInterface $paginator,
                                SeasonRepository $seasonRepository, RatingRepository $ratingRepository,
                                EpisodeRepository $episodeRepository, ExternalRatingRepository $externalRatingRepository,
                                EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
        $this->seriesRepository = $seriesRepository;
        $this->seasonRepository = $seasonRepository;
        $this->ratingRepository = $ratingRepository;
        $this->episodeRepository = $episodeRepository;
        $this->externalRatingRepository = $externalRatingRepository;
        $this->paginator = $paginator;
    }
}

templates/series/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/series/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ series.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/style-show-series.css') }}">
{% endblock %}

{% block body %}
    <div class="container" id="main-content">
        <div class="d-flex flex-column flex-lg-row">
            <div class="d-flex justify-content-center">
                {% set poster =  path('poster_show', {id : series.id}) %}
                <div>
                    <img id="poster" src="{{ poster }}" alt="poster">
                </div>
            </div>
            <div class="ml-lg-2 w-100">
                <div class="title d-flex flex-column flex-lg-row align-items-start align-items-lg-center justify-content-lg-between">
                    <span class="align-self-center text-nowrap">{{ series.title }}</span>
                    <div class="d-flex justify-content-between justify-content-lg-end w-100">
                        <a class="d-lg-none font-weight-bold text-decoration-none"
                           target="_blank" href="https://www.imdb.com/title/{{ series.imdb }}/">
                            <img class="imdb-logo" height="30" src="{{ asset('assets/img/IMDb-logo.svg') }}">
                        </a>
                        {% if is_granted('ROLE_USER') %}
                            {% if isSeriesFollowedByUser %}
                                <span title="{{ 'click_unfollow_series'|trans({'%series%':series.title}) }}"
                                      class="align-self-end align-self-lg-center">
                                <button data-series-id="{{ series.id }}" class="btn btn-success btn-sm btn-follow"
                                        type="submit">
                                    <div class="d">
                                        <ion-icon name="checkmark"></ion-icon>
                                    </div>
                                    <span class="spinner-border spinner-border-sm d-none"
                                          role="status" aria-hidden="true"></span>
                                </button>
                            </span>
                            {% else %}
                                <span title="{{ 'click_follow_series'|trans({'%series%':series.title}) }}"
                                      class="align-self-end align-self-lg-center">
                                    <button data-series-id="{{ series.id }}" class="btn btn-follow btn-info btn-sm"
                                            type="submit">
                                        <div class="d">
                                            <ion-icon name="add"></ion-icon>
                                        </div>
                                        <span class="spinner-border spinner-border-sm d-none" role="status"
                                              aria-hidden="true"></span>
                                    </button>
                                </span>
                            {% endif %}
                        {% else %}
                            <a href="{{ path('app_login') }}"
                               title="{{ 'log_to_follow'|trans({'%series%':series.title}) }}"
                               class="align-self-end align-self-lg-center">
                                <button data-series-id="{{ series.id }}" class="btn btn-info btn-sm"
                                        type="submit">
                                    <div class="d">
                                        <ion-icon name="add"></ion-icon>
                                    </div>
                                    <span class="spinner-border spinner-border-sm d-none" role="status"
                                          aria-hidden="true"></span>
                                </button>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="d-flex justify-content-between mt-2 mt-md-1">
                    <div class="d-flex">
                        <span>{{ series.yearStart }}</span>
                        {% if series.yearEnd %}
                            <span class="px-1">-</span>
                            <span>{{ series.yearEnd }}</span>
                        {% endif %}
                    </div>
                    {% if series.externalRating[0] is defined %}
                        {% set externalRating = series.externalRating[0] %}
                        {% if externalRating.source is defined and externalRating.votes is defined %}
                            <span title="{{ 'source_votes'|trans({'%name%':externalRating.source.name,'%vote%':externalRating.votes}) }}"
                                  class="font-weight-bold">{{ externalRating.value }}</span>
                        {% endif %}
                    {% else %}
                        <span class="font-weight-bold">NA</span>
                    {% endif %}
                </div>
                <p class="mt-3">{{ series.plot }}</p>
                <div class="d-flex flex-column">
                    <div class="d-flex justify-content-between mb-1">
                        <span>{{ 'genre'|trans }} : {{ series.genre|join(', ') }}.</span>
                        <a class="d-none d-lg-inline font-weight-bold text-decoration-none align-self-end"
                           target="_blank" href="https://www.imdb.com/title/{{ series.imdb }}/">
                            <img class="imdb-logo" height="30" src="{{ asset('assets/img/IMDb-logo.svg') }}">
                        </a>
                    </div>
                    <p>{{ 'casting'|trans }} : {{ series.actor | join(', ') }}...</p>
                    <p>{{ 'awards'|trans }} : {{ series.awards }}</p>

                </div>
            </div>
        </div>

        <section class="mt-4">
            <h2>{{ 'watch_trailer'|trans }}</h2>
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="{{ series.youtubeTrailerEmbed }}" allowfullscreen></iframe>
            </div>
        </section>
        <section class="mt-5">
            <h2 class="d-none"> {{ 'season'|trans }} - {{ 'episode'|trans }} </h2>
            <div class="container">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    <select aria-label="select-season" class="p-1 bg-dark text-white" id="select-season">
                        <optgroup label="{{ 'season'|trans }}">
                            {% for season in series.seasons %}
                                {% if season.episodes|length > 0 %}
                                    <option value="{{ season.number - 1 }}">{{ 'season'|trans }} {{ season.number }}</option>
                                {% endif %}
                            {% endfor %}
                        </optgroup>
                    </select>
                </div>
            </div>
            {% for season in series.seasons %}
                {% for episode in season.episodes %}
                    <div class="container season-{{ season.number-1 }} {% if season.number-1!=0 %}d-none{% endif %}">
                        <div class="row flex-row season-card mb-2">
                            <div class="col-auto d-flex justify-content-center poster-episode-container">
                                <img class="img-fluid poster-episode" src="{{ poster }}" alt="poster">
                            </div>
                            <div class="col">
                                <div>
                                    <div class="d-flex align-items-center">
                                        <span class="episode-number mr-4">{{ episode.number }}</span>
                                        <span class="title-episode">{{ episode.title }}</span>
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <span>{% if episode.date is not null %}{{ episode.date.format('Y-m-d') }}{% endif %}</span>
                                        <div class="d-flex justify-content-end align-items-center">
                                            {% if is_granted('ROLE_USER') %}
                                                {{ include('_eye_button.html.twig',{ 'watch':episode in episodesWatchedByUser,'isSeriesFollowedByUser':isSeriesFollowedByUser}) }}
                                            {% endif %}
                                            <span class="ml-1 episode-rating font-weight-bold">
                                                {% if episode.imdbrating is not empty %}
                                                    {{ episode.imdbrating }}/10
                                                {% else %}
                                                    {{ 'no_votes'|trans }}
                                                {% endif %}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </section>
        <section class="mt-5">
            <div class="container">
                <h2>{% if not isRatedByUser and is_granted('ROLE_USER') %}
                        {{ 'add_comment'|trans }}
                    {% else %}
                        {{ 'comments'|trans }}
                    {% endif %}
                </h2>
                {% if is_granted('ROLE_USER') %}
                    {% if not isRatedByUser %}
                        {% include 'rating/_form.html.twig' %}
                    {% endif %}
                {% else %}
                    <p>{{ 'log_to_comment'|trans }}</p>
                {% endif %}
            </div>
            {% if ratings.totalItemCount == 0 %}
                <div class="d-flex justify-content-center mt-4 mt-lg-5">
                    <span>{{ 'not_rating_yet'|trans }} ! :(</span>
                </div>
            {% else %}
                {% for rating in ratings %}
                    {{ include('_rating_show.html.twig') }}
                {% endfor %}
                <div class="d-flex justify-content-center">
                    {{ knp_pagination_render(ratings) }}
                </div>
            {% endif %}
        </section>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/bs-init-show-series.js') }}"></script>
    <script src="{{ asset('assets/js/watch.js') }}"></script>
    <script src="{{ asset('assets/js/follow.js') }}"></script>
    <script src="{{ asset('assets/js/title.js') }}"></script>
{% endblock %}